apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer-person
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-consumer-person
  template:
    metadata:
      labels:
        app: kafka-consumer-person
    spec:
      containers:
        - name: kafka-consumer-person
          image: abhirupaec2022/kafkapolller-persons:latest
          imagePullPolicy: Always
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-broker:9092"
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_NAME
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_PORT