# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: colour.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'colour.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63olour.proto\"\x1d\n\rColourRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1e\n\x0b\x43olourReply\x12\x0f\n\x07message\x18\x01 \x01(\t2=\n\x0e\x43olourProvider\x12+\n\tgetColour\x12\x0e.ColourRequest\x1a\x0c.ColourReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'colour_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COLOURREQUEST']._serialized_start=16
  _globals['_COLOURREQUEST']._serialized_end=45
  _globals['_COLOURREPLY']._serialized_start=47
  _globals['_COLOURREPLY']._serialized_end=77
  _globals['_COLOURPROVIDER']._serialized_start=79
  _globals['_COLOURPROVIDER']._serialized_end=140
# @@protoc_insertion_point(module_scope)
