# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import colour_pb2 as colour__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in colour_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ColourProviderStub(object):
    """The colour provider service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getColour = channel.unary_unary(
                '/ColourProvider/getColour',
                request_serializer=colour__pb2.ColourRequest.SerializeToString,
                response_deserializer=colour__pb2.ColourReply.FromString,
                _registered_method=True)


class ColourProviderServicer(object):
    """The colour provider service definition.
    """

    def getColour(self, request, context):
        """Sends a colour code
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ColourProviderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getColour': grpc.unary_unary_rpc_method_handler(
                    servicer.getColour,
                    request_deserializer=colour__pb2.ColourRequest.FromString,
                    response_serializer=colour__pb2.ColourReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ColourProvider', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ColourProvider', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ColourProvider(object):
    """The colour provider service definition.
    """

    @staticmethod
    def getColour(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ColourProvider/getColour',
            colour__pb2.ColourRequest.SerializeToString,
            colour__pb2.ColourReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
